```{r}
library(tidymodels)
library(tidyverse)
library(keras)
library(tensorflow)
library(e1071)
```

```{r}
load('../data/claims-clean-example.RData')
```


```{r}
claims_data <- claims_clean %>% select(.id, bclass, mclass, text_clean)

set.seed(9831)
partitions <- initial_split(claims_data, prop = 0.8)

train_text <- training(partitions) %>%
  pull(text_clean)
train_labels <- training(partitions) %>%
  pull(bclass)
train_labels_mclass <- training(partitions) %>%
  pull(mclass)

test_text <- testing(partitions) %>%
  pull(text_clean)
test_labels <- testing(partitions) %>%
  pull(bclass)
test_labels_mclass <- testing(partitions) %>%
  pull(mclass)
```

```{r}
preprocess_layer <- layer_text_vectorization(
  standardize = NULL,
  split = 'whitespace',
  ngrams = NULL,
  max_tokens = 7000,
  output_mode = 'tf_idf'
)

preprocess_layer %>% adapt(train_text)
```

```{r}
train_tfidf <- as.array(preprocess_layer(train_text))
test_tfidf <- as.array(preprocess_layer(test_text))
```

# Binary Classification

```{r}
# Fit binary SVM
svmfit_bclass = svm(x = train_tfidf,
             y = factor(train_labels),
             kernel = "linear", cost = 5, scale = FALSE)
print(svmfit_bclass)
```

```{r}
# compute predictions for binary

pred.bclass <- predict(svmfit_bclass, newdata = test_tfidf)


bclass_result <- tibble(
  .id = testing(partitions) %>% pull(.id),
  bclass = test_labels,
  pred.bclass = pred.bclass
)

conf_mat(bclass_result, truth = bclass, estimate = pred.bclass)
accuracy(bclass_result, truth = bclass, estimate = pred.bclass)
```


# Multiclass

```{r}
# Fit multiclass SVM
svmfit_mclass = svm(x = train_tfidf,
             y = factor(train_labels_mclass),
             kernel = "linear", cost = 5, scale = FALSE)
print(svmfit_mclass)
```

```{r}
# compute predictions for multiclass

pred.mclass <- predict(svmfit_mclass, newdata = test_tfidf)


mclass_result <- tibble(
  .id = testing(partitions) %>% pull(.id),
  mclass = test_labels_mclass,
  pred.mclass = pred.mclass
)

conf_mat(mclass_result, truth = mclass, estimate = pred.mclass)
accuracy(mclass_result, truth = mclass, estimate = pred.mclass)
```


# Save models to results/SVM-Model
```{r}
# saveRDS(svmfit_bclass, file = "../results/SVM-Model/svm_bclass.rds")
# saveRDS(svmfit_mclass, file = "../results/SVM-Model/svm_mclass.rds")
```

# Create pred_df on test data

```{r}
load('../data/claims-test.RData')
source('../scripts/preprocessing.R')

prop <- 0.16
set.seed(1192)
claims_test_subset <- claims_test[sample(nrow(claims_test), size = floor(prop * nrow(claims_test))), ]
claims_test_subset_clean <- claims_test_subset %>% parse_data()

claims_test_text <- claims_test_subset_clean$text_clean

claims_test_tfidf <- as.array(preprocess_layer(claims_test_text))

pred.bclass <- predict(svmfit_bclass, newdata = claims_test_tfidf)
pred.mclass <- predict(svmfit_mclass, newdata = claims_test_tfidf)

pred_df <- data.frame(
  .id = claims_test_subset_clean %>% pull(.id),
  bclass.pred = pred.bclass,
  mclass.pred = pred.mclass
)

save(pred_df, file = "../results/preds-group3.RData")
```

